---

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.7.2
    container_name: homeassistant
    restart: always
    volumes:
      - ${COMPOSE_ROOT_PATH}/homeassistant:/config:z
