---

services:
  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter
    restart: always
    pid: host
    volumes:
      - '/:/rootfs:ro,rslave,z'
    command:
      - '--path.rootfs=/rootfs'
      #- '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
