---
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.153.0
    container_name: victoriametrics
    volumes:
      - ${COMPOSE_ROOT_PATH}/victoriametrics:/storage:z
    command:
      - "--storageDataPath=/storage"
      - "--retentionPeriod=6M"
      - "--vmalert.proxyURL=http://vmalert:8880"
    restart: always
